name: Linux, Windows, macOS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    name: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: mkdir
        run: mkdir build

      - name: configure
        working-directory: ./build
        run: cmake -DCMAKE_BUILD_TYPE='Debug' ..

      - name: build
        working-directory: ./build
        run: cmake --build .

      - name: test
        working-directory: ./build
        run: ctest -C Debug .
